spring.application.name=url-shortner

server.port=${PORT:8080}
app.base-url=${APP_BASE_URL:http://localhost:8080}

spring.datasource.url=jdbc:postgresql://${PGHOST:localhost}:${PGPORT:5432}/${PGDATABASE:url_shortner}
spring.datasource.username=${PGUSER:postgres}
spring.datasource.password=${PGPASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.profiles.active=local